### ISSUE TITLE
Temporary database for debug

### ISSUE THREAD

**Issue by Kolonsky** [thecorecity/cognitum#15]
Need to implement in-memory database for debug, instead of connecting to an existing database.

**Comment by Kolonsky** [comment]
There is no need to use an in-memory database. A local connection to a temporary database will be used instead.

**Comment by koloml** [comment]
That's much better. Also, we can use migrations (#3) in future both for live database and local database.

**Comment by Kolonsky** [comment]
- [ ] #21 db.schema.json
