### ISSUE TITLE
Base language pack version on child packs

### ISSUE THREAD

**Issue by koloml** [thecorecity/cognitum#22]
We have base language pack — english. So any other language packs just translates everything from this pack. I think we need to set special meta-value about implemented version of english language pack.

**Comment by koloml** [comment]
Oh, and for sure, need to update related JSON schema for language packs.

**Comment by Kolonsky** [comment]
> 
> 
> Oh, and for sure, need to update related JSON schema for language packs.

You want to update schema every time you update en.json pack? I mean, every version?
