### ISSUE TITLE
Database structure rebuild, migrations for new database structure

### ISSUE THREAD

**Issue by koloml** [thecorecity/cognitum#3]
We have `sequelize` ORM module for accessing database. This module includes migration feature for making changes in real database on every bot updates. So we need:

+ Create first initial migration with current database state.
+ Add information about creating and applying migrations to README file.

Migrations folder must be in this folder: `/lib/database/migrations/`.

**Comment by koloml** [comment]
We need `sequelize-cli` for applying new migrations. We can make it in two different ways:

+ Installing `sequelize-cli` to project as `dependency` (not `devDependency`)
+ Manual installaton to server

**Comment by koloml** [comment]
@Kolonsky as soon as you will ready to send any information about new database structure send here.

**Comment by Kolonsky** [comment]
Made new database structure. ![Database structure](https://cdn.discordapp.com/attachments/726484907433656383/731955895092772874/unknown.png)
