### ISSUE TITLE
JSON files in config folder and JSON schemas

### ISSUE THREAD

**Issue by Kolonsky** [thecorecity/cognitum#8]
JSON files in config folder do not reference existing schema files.

**Comment by Kolonsky** [comment]
Also lang files do not reference existing schema files too.

**Comment by koloml** [comment]
Is `Invalid` label made for this. I forgot.

**Comment by koloml** [comment]
Maybe `invalid` label is related to issue, not a thing that this issue talking about?

**Comment by Kolonsky** [comment]
> 
> 
> Is `Invalid` label made for this. I forgot.

@koloml Have I misunderstood the meaning of this tag?
